branches:
  only:
  - master
  - /^RELEASE.*$/
language: java
jdk:
- oraclejdk8
before_install:
- ls -la
before_cache:
  - rm -rf $HOME/.m2/repository/
cache:
  directories:
  - $HOME/.m2/repository
script:
   - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash mvn release:prepare && mvn release:perform; fi'
   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash mvn test -B; fi'
   
